/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import domain.Prijava;
import domain.User;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import network.Request;
import network.RequestType;
import network.Response;

/**
 *
 * @author vuk
 */
public class DodajPrijavuFrm extends javax.swing.JDialog {
    
    private Socket socket;
    private ObjectOutputStream out;
    private ObjectInputStream in;
    private User user;
    private Prijava p;
    private static final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");
    /**
     * Creates new form DodajPrijavuFrm
     */
    public DodajPrijavuFrm(java.awt.Frame parent, boolean modal, Socket socket, ObjectInputStream in, ObjectOutputStream out) {
        super(parent, modal);
        initComponents();
        this.socket = socket;
        this.out = out;
        this.in = in;
        jButtonIzmeni.setEnabled(false);
        jButtonIzmeni.setVisible(false);
    }
    
    
    public DodajPrijavuFrm(java.awt.Frame parent, boolean modal, Socket socket, ObjectInputStream in, ObjectOutputStream out, User user) {
        super(parent, modal);
        initComponents();
        this.socket = socket;
        this.out = out;
        this.in = in;
        this.user = user;
        jButtonIzmeni.setEnabled(false);
        jButtonIzmeni.setVisible(false);
        if(user != null){
                jTextFieldIme.setText(user.getIme());
                jTextFieldIme.setEnabled(false);
                jTextFieldPrezime.setText(user.getPrezime());
                jTextFieldPrezime.setEnabled(false);
                jTextFieldJMBG.setText(user.getJmbg());
                jTextFieldJMBG.setEnabled(false);
                jTextFieldEmail.setText(user.getEmail());
                jTextFieldEmail.setEnabled(false);
        }
    }
    
    public DodajPrijavuFrm(java.awt.Frame parent, boolean modal, Socket socket, ObjectInputStream in, ObjectOutputStream out, Prijava p) {
        super(parent, modal);
        initComponents();
        this.socket = socket;
        this.out = out;
        this.in = in;
        this.p = p;
        jButtonDodaj.setEnabled(false);
        jButtonDodaj.setVisible(false);
        if(p != null){
                jTextFieldIme.setText(p.getIme());
                jTextFieldIme.setEnabled(false);
                jTextFieldPrezime.setText(p.getPrezime());
                jTextFieldPrezime.setEnabled(false);
                jTextFieldJMBG.setText(p.getJmbg());
                jTextFieldJMBG.setEnabled(false);
                jTextFieldEmail.setText(p.getEmail());
                jTextFieldEmail.setEnabled(false);
                String datumZaPrikaz = p.getDatumVol().format(formatter);
                jTextFieldDatVol.setText(datumZaPrikaz);
                jComboBoxSmena.setSelectedItem(p.getSmena());
                jComboBoxPozicija.setSelectedItem(p.getPozicija());
        }
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldIme = new javax.swing.JTextField();
        jTextFieldPrezime = new javax.swing.JTextField();
        jTextFieldJMBG = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldDatVol = new javax.swing.JTextField();
        jComboBoxSmena = new javax.swing.JComboBox<>();
        jComboBoxPozicija = new javax.swing.JComboBox<>();
        jButtonDodaj = new javax.swing.JButton();
        jButtonQuit = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        jLabel3.setText("JMBG");

        jLabel4.setText("Email");

        jLabel5.setText("Datum Volontiranja");

        jLabel6.setText("Smena");

        jLabel7.setText("Pozicija");

        jTextFieldDatVol.setText("dd.mm.yyyy");

        jComboBoxSmena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jutarnja", "Popodnevna", "Vecernja" }));
        jComboBoxSmena.setSelectedIndex(-1);

        jComboBoxPozicija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Osoblje za informacije", "Redar", "Mediji", "Posluga u VIP zoni" }));
        jComboBoxPozicija.setSelectedIndex(-1);

        jButtonDodaj.setText("Dodaj prijavu");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jButtonQuit.setText("Odustani");
        jButtonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitActionPerformed(evt);
            }
        });

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDatVol, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldJMBG)
                                        .addComponent(jTextFieldEmail))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxSmena, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jButtonDodaj)
                        .addGap(37, 37, 37)
                        .addComponent(jButtonQuit)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIzmeni)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDatVol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxSmena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxPozicija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodaj)
                    .addComponent(jButtonQuit)
                    .addComponent(jButtonIzmeni))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitActionPerformed
        // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_jButtonQuitActionPerformed

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        // TODO add your handling code here:
        try {

            validirajPolja();

            Prijava newPrijava = new Prijava();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");

            if (user == null) {

                newPrijava.setIme(jTextFieldIme.getText().trim());
                newPrijava.setPrezime(jTextFieldPrezime.getText().trim());
                newPrijava.setJmbg(jTextFieldJMBG.getText().trim());
                newPrijava.setEmail(jTextFieldEmail.getText().trim());
            } else {

                newPrijava.setIme(user.getIme());
                newPrijava.setPrezime(user.getPrezime());
                newPrijava.setJmbg(user.getJmbg());
                newPrijava.setEmail(user.getEmail());
            }

            newPrijava.setDatumVol(LocalDate.parse(jTextFieldDatVol.getText().trim(), formatter));
            newPrijava.setSmena(jComboBoxSmena.getSelectedItem().toString());
            newPrijava.setPozicija(jComboBoxPozicija.getSelectedItem().toString());
            newPrijava.setDatumPrij(LocalDate.now());

            posaljiZahtev(newPrijava);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Greška", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        // TODO add your handling code here:
        try {
        
            validirajPolja();
            
            String datumText = jTextFieldDatVol.getText().trim();
            LocalDate datum = LocalDate.parse(datumText, formatter);

            p.setDatumVol(datum);
            p.setSmena(jComboBoxSmena.getSelectedItem().toString());
            p.setPozicija(jComboBoxPozicija.getSelectedItem().toString());

            posaljiUpdateRequest();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        this.dispose();    
        }
    }//GEN-LAST:event_jButtonIzmeniActionPerformed
    
    private void generisiTxtPotvrdu(Prijava p) {
        String nazivFajla = "Potvrda_" + p.getJmbg() + "_" + System.currentTimeMillis() + ".txt";
        try (java.io.PrintWriter writer = new java.io.PrintWriter(new java.io.FileWriter(nazivFajla))) {
            writer.println("==========================================");
            writer.println("   AUSTRALIAN OPEN - POTVRDA PRIJAVE");
            writer.println("==========================================");
            writer.println("Ime i prezime: " + p.getIme() + " " + p.getPrezime());
            writer.println("JMBG:          " + p.getJmbg());
            writer.println("Pozicija:      " + p.getPozicija());
            writer.println("Smena:         " + p.getSmena());
            writer.println("Datum rada:    " + p.getDatumVol());
            writer.println("Datum prijave: " + p.getDatumPrij());
            writer.println("------------------------------------------");
            writer.println("Status: USPESNO SACUVANO U BAZI");
            writer.println("==========================================");


        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Greška pri pravljenju fajla!");
        }
    }
    
    private void validirajPolja() throws Exception {
        String ime = jTextFieldIme.getText().trim();
        String prezime = jTextFieldPrezime.getText().trim();
        String jmbg = jTextFieldJMBG.getText().trim();
        String email = jTextFieldEmail.getText().trim();
        String datumVolStr = jTextFieldDatVol.getText().trim();

        if (ime.isEmpty() || prezime.isEmpty() || jmbg.isEmpty() || email.isEmpty() || datumVolStr.isEmpty()) {
            throw new Exception("Sva polja moraju biti popunjena!");
        }

        if (ime.length() < 2) throw new Exception("Ime mora imati bar 2 karaktera!");
        if (prezime.length() < 2) throw new Exception("Prezime mora imati bar 2 karaktera!");

        if (!jmbg.matches("\\d{13}")) {
            throw new Exception("JMBG mora imati tačno 13 cifara!");
        }

        if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}$")) {
            throw new Exception("Email format nije ispravan!");
        }

        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd.MM.yyyy");
            LocalDate datVol = LocalDate.parse(datumVolStr, formatter);

            if (datVol.isBefore(LocalDate.now().plusDays(1))) {
                throw new Exception("Datum volontiranja mora biti barem sutrašnji dan!");
            }
            if (datVol.isAfter(LocalDate.of(2026, 2, 5))) {
                throw new Exception("Datum volontiranja ne može biti posle 05.02.2026.");
            }
        } catch (java.time.format.DateTimeParseException e) {
            throw new Exception("Datum mora biti u formatu dd.mm.yyyy");
        }

        if (jComboBoxSmena.getSelectedIndex() == -1) throw new Exception("Izaberite smenu!");
        if (jComboBoxPozicija.getSelectedIndex() == -1) throw new Exception("Izaberite poziciju!");
    }
    
    private void posaljiZahtev(Prijava p) {
        new Thread(() -> {
            try {
                Request req = new Request(RequestType.ADD, p);
                out.writeObject(req);
                out.flush();

                Response resp = (Response) in.readObject();

                java.awt.EventQueue.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, resp.getMessage());
                    if (resp.isSuccess()) {
                        generisiTxtPotvrdu(p);
                        this.dispose();
                    }
                });
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();
    }
    
     private void posaljiUpdateRequest() {
        new Thread(() -> {
            try {
                out.reset();
                Request req = new Request(RequestType.EDIT, p);
                out.writeObject(req);
                out.flush();

                Response resp = (Response) in.readObject();

                java.awt.EventQueue.invokeLater(() -> {
                    JOptionPane.showMessageDialog(this, resp.getMessage());
                    if (resp.isSuccess()) {
                        generisiTxtPotvrdu(p);
                        this.dispose();
                    }
                });
            } catch (Exception e) {
                e.printStackTrace();
            }
        }).start();
    }
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JComboBox<String> jComboBoxPozicija;
    private javax.swing.JComboBox<String> jComboBoxSmena;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldDatVol;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldIme;
    private javax.swing.JTextField jTextFieldJMBG;
    private javax.swing.JTextField jTextFieldPrezime;
    // End of variables declaration//GEN-END:variables

   
}
