/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import domain.User;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import network.Request;
import network.RequestType;

/**
 *
 * @author vuk
 */
public class MainFormImaNalog extends javax.swing.JFrame {
    
    private User loggedInUser;
    private Socket socket;
    private ObjectOutputStream out;
    private ObjectInputStream in;
    
    
    
    /**
     * Creates new form MainForm
     */
    public MainFormImaNalog(Socket socket, ObjectInputStream in, ObjectOutputStream out, User user) {
        initComponents();
        this.loggedInUser = user;
        this.socket = socket;
        this.out = out;
        this.in = in;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDodajPrijavu = new javax.swing.JButton();
        jButtonVidiPrijave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonQuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonDodajPrijavu.setText("Dodaj prijavu");
        jButtonDodajPrijavu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajPrijavuActionPerformed(evt);
            }
        });

        jButtonVidiPrijave.setText("VIdi prijave");
        jButtonVidiPrijave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVidiPrijaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Dobrodošli, trenutno ste prijavljeni na svoj nalog");

        jButtonQuit.setText("Izađi");
        jButtonQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonDodajPrijavu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonVidiPrijave))
                            .addComponent(jLabel1))
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonQuit)
                        .addGap(176, 176, 176))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDodajPrijavu)
                    .addComponent(jButtonVidiPrijave))
                .addGap(18, 18, 18)
                .addComponent(jButtonQuit)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuitActionPerformed
        // TODO add your handling code here:
        try {
            Request req = new Request();
            req.setType(RequestType.LOGOUT);
            out.writeObject(req);
            out.flush();
            in.close();
            out.close();
            socket.close();
            System.exit(0);
        
    } catch (IOException e) {
        
    }     
    }//GEN-LAST:event_jButtonQuitActionPerformed

    private void jButtonDodajPrijavuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajPrijavuActionPerformed
        // TODO add your handling code here:
        if (socket == null || socket.isClosed()) {
            JOptionPane.showMessageDialog(this, "Niste povezani na server!");
            return;
        }
        try {
            DodajPrijavuFrm dpf = new DodajPrijavuFrm(this, true, socket, in, out, loggedInUser);
            dpf.setVisible(true);
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButtonDodajPrijavuActionPerformed

    private void jButtonVidiPrijaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVidiPrijaveActionPerformed
        // TODO add your handling code here:
            TekuceForma tfm = new TekuceForma(socket, in, out, loggedInUser);
            JDialog dialog = new JDialog((JFrame)null, "Vaše prijave", true);
            dialog.add(tfm);
            dialog.pack();
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true); 
    }//GEN-LAST:event_jButtonVidiPrijaveActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajPrijavu;
    private javax.swing.JButton jButtonQuit;
    private javax.swing.JButton jButtonVidiPrijave;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
