/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import network.Request;
import network.RequestType;
import network.Response;

/**
 *
 * @author vuk
 */
public class PopupFrm extends javax.swing.JDialog {
    private Socket socket;
    private ObjectOutputStream out;
    private ObjectInputStream in;
    

    /**
     * Creates new form PopupFrm
     */
    public PopupFrm(java.awt.Frame parent, boolean modal, Socket socket, ObjectInputStream in, ObjectOutputStream out) {
        super(parent, modal);
        initComponents();
        this.socket = socket;
        this.out = out;
        this.in = in;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldJmbg = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonNastavi = new javax.swing.JButton();
        jButtonOdustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pristupte kao guest molimo vas unesite jbmg i email");

        jLabel2.setText("Email");

        jLabel3.setText("JMBG");

        jButtonNastavi.setText("Nastavi");
        jButtonNastavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNastaviActionPerformed(evt);
            }
        });

        jButtonOdustani.setText("Odustani");
        jButtonOdustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOdustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonNastavi)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonOdustani)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNastavi)
                    .addComponent(jButtonOdustani))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOdustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOdustaniActionPerformed
        // TODO add your handling code here:
        this.dispose();    
    }//GEN-LAST:event_jButtonOdustaniActionPerformed

    private void jButtonNastaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNastaviActionPerformed
        // TODO add your handling code here:
        String JMBG = jTextFieldJmbg.getText();
        String email = jTextFieldEmail.getText();
        
        if((JMBG != null && JMBG.length() == 13 && JMBG.matches("\\d+"))
            && (email != null && email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}$"))){
            try {
                String[] podacizaSlanje = {JMBG, email};
                out.writeObject(new Request(RequestType.CHECK, podacizaSlanje));
                out.flush();

                Response resp = (Response) in.readObject();

                if (resp.isSuccess()) {

                    TekuceForma tfm = new TekuceForma(socket, in, out, JMBG, email);
                    JDialog dialog = new JDialog((JFrame)null, "Vaše prijave", true);
                    dialog.add(tfm);
                    dialog.pack();
                    dialog.setLocationRelativeTo(null);

                    this.dispose();
                    dialog.setVisible(true); 
                } else {
                    JOptionPane.showMessageDialog(this, resp.getMessage(), "Nema podataka", JOptionPane.WARNING_MESSAGE);
                }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Greška u komunikaciji: " + e.getMessage());
        }
        }else{
            JOptionPane.showMessageDialog(this, "JMBG ili email nisu uneti korektno");
        }
    }//GEN-LAST:event_jButtonNastaviActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNastavi;
    private javax.swing.JButton jButtonOdustani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldJmbg;
    // End of variables declaration//GEN-END:variables
}
