/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import domain.Prijava;
import domain.PrijavaTableModel;
import domain.User;
import java.awt.EventQueue;
import java.awt.Frame;
import java.awt.Window;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import network.Request;
import network.RequestType;
import network.Response;


/**
 *
 * @author vuk
 */
public class TekuceForma extends javax.swing.JPanel {
    private Socket socket;
    private ObjectOutputStream out;
    private ObjectInputStream in;
    private User user;
    private String jmbg, email;
    private PrijavaTableModel model;
    
    /**
     * Creates new form TekuceForma
     */
    public TekuceForma(Socket socket, ObjectInputStream in, ObjectOutputStream out, String jmbg, String email) {
        initComponents();
        this.socket = socket;
        this.out = out;
        this.in = in;
        this.jmbg = jmbg;
        this.email = email;
        
        podesiInterfejsZaTipKorisnika();
        inicijalizujTabelu();
        popuniTabeluSaServera();
    }
    
    public TekuceForma(Socket socket, ObjectInputStream in, ObjectOutputStream out, User user) {
        initComponents();
        this.socket = socket;
        this.out = out;
        this.in = in;
        this.user = user;
        this.jmbg = user.getJmbg();
        this.email = user.getEmail();
        
        podesiInterfejsZaTipKorisnika();
        inicijalizujTabelu();
        popuniTabeluSaServera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonObrisi = new javax.swing.JButton();
        jButtonZatvori = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Tekuce prijave");

        jButton1.setText("Izmeni prijavu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonObrisi.setText("Obriši prijavu");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonZatvori.setText("Zatvori");
        jButtonZatvori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZatvoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonObrisi)
                .addGap(27, 27, 27)
                .addComponent(jButtonZatvori)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButtonObrisi)
                    .addComponent(jButtonZatvori))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void podesiInterfejsZaTipKorisnika() {
        if (user == null) {
            jButton1.setVisible(false);
            jButtonObrisi.setVisible(false);
            jLabel1.setText("Tekuće prijave (Guest mod - samo pregled)");
        } else {
            jButton1.setEnabled(false);
            jButtonObrisi.setEnabled(false);
            jLabel1.setText("Upravljanje prijavama: " + user.getIme());
        }
    }

    private void inicijalizujTabelu() {
        model = new PrijavaTableModel(new ArrayList<>());
        jTable1.setModel(model);
        
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            proveriDostupnostAkcija();
        });
    }

    private void proveriDostupnostAkcija() {
        if (user == null) return;

        int red = jTable1.getSelectedRow();
        if (red != -1) {
            Prijava p = model.getPrijavaAt(red);
            boolean mozeAkcija = p.getStatus().equals("U obradi");
            jButton1.setEnabled(mozeAkcija);
            jButtonObrisi.setEnabled(mozeAkcija);
        }
    }

    public void popuniTabeluSaServera() {
        new Thread(() -> {
        try {
            System.out.println("DEBUG: Pokrećem LOAD...");
            System.out.println("DEBUG: Šaljem parametre -> JMBG: " + jmbg + ", Email: " + email);

            Request req = new Request(RequestType.LOAD, new String[]{jmbg, email});
            out.writeObject(req);
            out.flush();

            Response res = (Response) in.readObject();
            
            if (res.isSuccess()) {
                List<Prijava> lista = res.getPrijave();
                
                if (lista == null || lista.isEmpty()) {
                    System.out.println("DEBUG: Server je vratio USPEH, ali je LISTA PRAZNA (0 rezultata u bazi).");
                } else {
                    System.out.println("DEBUG: Stiglo je " + lista.size() + " prijava.");
                }

                EventQueue.invokeLater(() -> {
                    model.osveziPodatke(lista);
                    jTable1.setModel(model); 
                    model.fireTableDataChanged();
                });
            } else {
                System.out.println("DEBUG: Server vratio GREŠKU: " + res.getMessage());
            }
        } catch (Exception e) {
            System.out.println("DEBUG: EXCEPTION na klijentu: " + e.getMessage());
            e.printStackTrace();
        }
    }).start();
    }
    
    
    private void jButtonZatvoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZatvoriActionPerformed
        // TODO add your handling code here:
        Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow != null) {
            parentWindow.dispose();
        }
    }//GEN-LAST:event_jButtonZatvoriActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Molimo vas, selektujte prijavu za brisanje.");
            return;
        }
        
        PrijavaTableModel model = (PrijavaTableModel) jTable1.getModel();
        Prijava p = model.getPrijavaAt(row);
        
         if (!p.getStatus().equals("U obradi")) {
            JOptionPane.showMessageDialog(this, "Možete brisati samo prijave koje su u statusu 'U obradi'!");
            return;
        }


        int confirm = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da želite da obrišete prijavu?", "Potvrda", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            new Thread(() -> {
                try {
                    Request req = new Request(RequestType.DEL, p);
                    out.writeObject(req);
                    out.flush();

                    Response resp = (Response) in.readObject();

                    java.awt.EventQueue.invokeLater(() -> {
                        JOptionPane.showMessageDialog(this, resp.getMessage());
                        if (resp.isSuccess()) {
                           popuniTabeluSaServera();
                        }
                    });
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }).start();
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Molimo vas, selektujte prijavu za izmenu.");
            return;
        }

        Prijava p = model.getPrijavaAt(row);

        // Ista provera statusa kao kod brisanja
        if (!p.getStatus().equals("U obradi")) {
            JOptionPane.showMessageDialog(this, "Možete menjati samo prijave koje su u statusu 'U obradi'!");
            return;
        }

        DodajPrijavuFrm izmenaFrm = new DodajPrijavuFrm(null, true, socket, in, out, p);
        izmenaFrm.setLocationRelativeTo(this);
        izmenaFrm.setAlwaysOnTop(true);
        izmenaFrm.setVisible(true);

        popuniTabeluSaServera();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonZatvori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
